-- REVISAO SUPABASE REAL: substitui a versao anterior, que NAO foi aplicada.
-- Aplicar SOMENTE apos aprovacao do plano PLANO_MIGRACAO_SUPABASE.md.
-- usuarios permanece a unica origem de identidade, senha e dados profissionais.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

DO $$ BEGIN
    IF to_regclass('public.usuarios') IS NULL OR to_regclass('public.tarefas') IS NULL THEN
        RAISE EXCEPTION 'Banco inesperado: usuarios e tarefas existentes sao obrigatorias.';
    END IF;
    IF to_regclass('public.profissionais') IS NOT NULL THEN
        RAISE EXCEPTION 'A migration antiga foi aplicada ou o schema mudou. Revisar os dados de profissionais antes de continuar; nenhuma tabela sera removida.';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'usuarios'
            AND column_name = 'id' AND data_type = 'bigint') THEN
        RAISE EXCEPTION 'usuarios.id deve ser BIGINT, conforme o preflight aprovado.';
    END IF;
END $$;

ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'paciente';
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS ativo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS auth_version INTEGER NOT NULL DEFAULT 0;
-- Sem DEFAULT na inclusao: a data historica desconhecida dos usuarios antigos fica NULL.
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS criado_em TIMESTAMPTZ;
ALTER TABLE public.usuarios ALTER COLUMN criado_em SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS registro VARCHAR(60);
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS especialidade VARCHAR(120);
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS perfil_profissional_ativo BOOLEAN NOT NULL DEFAULT FALSE;

-- Nao sobrescreve roles ja concedidas. Valores incompatíveis interrompem a transacao.
UPDATE public.usuarios SET role = 'paciente' WHERE role IS NULL;
ALTER TABLE public.usuarios ALTER COLUMN role SET DEFAULT 'paciente';
ALTER TABLE public.usuarios ALTER COLUMN role SET NOT NULL;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.usuarios'::regclass
        AND conname = 'usuarios_role_unico_check') THEN
        ALTER TABLE public.usuarios ADD CONSTRAINT usuarios_role_unico_check
            CHECK (role IN ('paciente', 'psicologo', 'admin'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.usuarios'::regclass
        AND conname = 'usuarios_perfil_profissional_check') THEN
        ALTER TABLE public.usuarios ADD CONSTRAINT usuarios_perfil_profissional_check CHECK (
            (role <> 'psicologo' OR (registro IS NOT NULL AND length(btrim(registro)) > 0))
            AND (NOT perfil_profissional_ativo OR role = 'psicologo')
        );
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.profissional_pacientes (
    profissional_id BIGINT NOT NULL REFERENCES public.usuarios(id),
    paciente_id BIGINT NOT NULL REFERENCES public.usuarios(id),
    vinculado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    desvinculado_em TIMESTAMPTZ,
    PRIMARY KEY (profissional_id, paciente_id),
    CHECK (profissional_id <> paciente_id),
    CHECK ((ativo AND desvinculado_em IS NULL) OR (NOT ativo AND desvinculado_em IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS profissional_pacientes_paciente
    ON public.profissional_pacientes(paciente_id);

CREATE TABLE IF NOT EXISTS public.consultas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profissional_id BIGINT NOT NULL,
    paciente_id BIGINT NOT NULL,
    inicio TIMESTAMPTZ NOT NULL,
    tipo VARCHAR(40) NOT NULL CHECK (tipo IN ('Consulta psicológica', 'Retorno')),
    status VARCHAR(20) NOT NULL DEFAULT 'agendada'
        CHECK (status IN ('agendada', 'confirmada', 'em_atendimento', 'finalizada', 'cancelada')),
    FOREIGN KEY (profissional_id, paciente_id)
        REFERENCES public.profissional_pacientes(profissional_id, paciente_id)
);
CREATE INDEX IF NOT EXISTS consultas_profissional_inicio ON public.consultas(profissional_id, inicio);
CREATE INDEX IF NOT EXISTS consultas_paciente ON public.consultas(profissional_id, paciente_id, inicio);
CREATE UNIQUE INDEX IF NOT EXISTS consultas_horario_ativo ON public.consultas(profissional_id, inicio)
    WHERE status <> 'cancelada';

-- Sem policies publicas. O backend tem BYPASSRLS e autoriza no Flask/SQL.
ALTER TABLE public.profissional_pacientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consultas ENABLE ROW LEVEL SECURITY;
COMMIT;
