-- REVISAO SUPABASE REAL: aplicar SOMENTE apos confirmacao, depois da 001 revisada.
-- Nao cria identidades, nao promove administradores e nao altera senhas.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

DO $$ BEGIN
    IF to_regclass('public.profissionais') IS NOT NULL OR
        NOT EXISTS (SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'usuarios'
                AND column_name = 'perfil_profissional_ativo') OR
        to_regclass('public.profissional_pacientes') IS NULL OR
        to_regclass('public.consultas') IS NULL THEN
        RAISE EXCEPTION 'Aplicar primeiro a migration 001 revisada, com identidade unica em usuarios.';
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.auditoria_admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    administrador_id BIGINT REFERENCES public.usuarios(id),
    acao VARCHAR(60) NOT NULL,
    usuario_afetado_id BIGINT REFERENCES public.usuarios(id),
    profissional_id BIGINT REFERENCES public.usuarios(id),
    paciente_id BIGINT REFERENCES public.usuarios(id),
    detalhes JSONB NOT NULL DEFAULT '{}'::jsonb,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS auditoria_admin_criado_em ON public.auditoria_admin(criado_em DESC);
CREATE INDEX IF NOT EXISTS auditoria_admin_administrador ON public.auditoria_admin(administrador_id, criado_em DESC);

-- RLS fecha o caminho publico; Flask/SQL isola usuarios na conexao com BYPASSRLS.
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tarefas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.auditoria_admin ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.usuarios, public.tarefas, public.profissional_pacientes,
    public.consultas, public.auditoria_admin FROM PUBLIC;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON public.usuarios, public.tarefas, public.profissional_pacientes,
            public.consultas, public.auditoria_admin FROM anon;
        REVOKE ALL ON SEQUENCE public.consultas_id_seq, public.auditoria_admin_id_seq FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON public.usuarios, public.tarefas, public.profissional_pacientes,
            public.consultas, public.auditoria_admin FROM authenticated;
        REVOKE ALL ON SEQUENCE public.consultas_id_seq, public.auditoria_admin_id_seq FROM authenticated;
    END IF;
END $$;
REVOKE ALL ON SEQUENCE public.consultas_id_seq, public.auditoria_admin_id_seq FROM PUBLIC;
COMMIT;
